version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  maven: circleci/maven@1.4.1
  kubernetes: circleci/kubernetes@1.3.0

jobs:
  create-update:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install-kubectl
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: k8s-manifest.yml
          show-kubectl-command: true

workflows:
  java_demo_test_build_deploy:
    jobs:
      - maven/test:
          name: code-test
          filters:
            branches:
              only:
                - main
          executor:
            name: maven/default
            tag: 17.0.7
          command: 'clean test'
      - aws-ecr/build-and-push-image:
          name: build-push-image
          filters:
            branches:
              only:
                - main
          repo: "${AWS_ECR_REGISTRY_NAME}"
          tag: "latest"
          dockerfile: Dockerfile-run
          path: .
          requires:
            - code-test
      - create-update:
          name: deploy-to-k8s
          filters:
            branches:
              only:
                - main
          requires:
            - build-push-image
