version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  maven: circleci/maven@1.4.1

workflows:
  test_build_and_push_image:
    jobs:
      - maven/test:
          name: code-test
          filters:
            branches:
              only:
                - main
      - aws-ecr/build-and-push-image:
          name: build-push-image
          filters:
            branches:
              only:
                - main
          repo: "${AWS_ECR_REGISTRY_NAME}"
          tag: "latest"
          dockerfile: Dockerfile-run
          path: .
          requires:
            - code-test