version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  maven: circleci/maven@1.4.1
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  create-deployment:
    docker:
      - image: cimg/python:3.10
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      region:
        description: |
          AWS Region of the EKS cluster
        type: string
      ecr-id:
        description: |
          AWS Account ID
        type: string
    steps:
      - checkout
      - run:
          name: AWS and kubectl config
          command: |
            sudo apt-get update -y
            sudo apt-get install awscli groff -y
            pip install awscli
            sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - run:
          name: Configure AWS
          command: |
            aws configure set default.region << parameters.region >>
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region << parameters.region >> | docker login --username AWS --password-stdin << parameters.ecr-id >>.dkr.ecr.<< parameters.region >>.amazonaws.com
      - run:
          name: Configure Kubectl
          command: |
            aws eks update-kubeconfig --region us-west-2 --name iap-tmp-eks
      - run:
          name: Apply k8s manifest
          command: |
            kubectl apply -t java-demo -f k8s-manifest.yml

workflows:
  java_demo_test_build_deploy:
    jobs:
#      - maven/test:
#          name: code-test
#          filters:
#            branches:
#              only:
#                - main
#          executor:
#            name: maven/default
#            tag: 17.0.7
#          command: 'clean test'
#      - aws-ecr/build-and-push-image:
#          name: build-push-image
#          filters:
#            branches:
#              only:
#                - main
#          repo: "${AWS_ECR_REGISTRY_NAME}"
#          tag: "latest"
#          dockerfile: Dockerfile-run
#          path: .
#          requires:
#            - code-test
      - create-deployment:
          name: deploy-to-k8s
          filters:
            branches:
              only:
                - main
          cluster-name: "${AWS_EKS_CLUSTER_NAME}"
          region: "${AWS_REGION}"
          ecr-id: "${AWS_ECR_REGISTRY_ID}"
#          requires:
#            - build-push-image
